//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Walkabout.RestfulWebServices {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CurrencyCode", Namespace="http://www.restfulwebservices.net/DataContracts/2008/01")]
    public enum CurrencyCode : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AFA = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ALL = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DZD = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ARS = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AWG = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AUD = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BSD = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BHD = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BDT = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BBD = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BZD = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BMD = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BTN = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BOB = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BWP = 14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BRL = 15,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GBP = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BND = 17,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BIF = 18,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        XOF = 19,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        XAF = 20,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        KHR = 21,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CAD = 22,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CVE = 23,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        KYD = 24,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CLP = 25,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CNY = 26,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        COP = 27,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        KMF = 28,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CRC = 29,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HRK = 30,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CUP = 31,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CYP = 32,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CZK = 33,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DKK = 34,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DJF = 35,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DOP = 36,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        XCD = 37,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EGP = 38,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SVC = 39,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EEK = 40,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ETB = 41,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EUR = 42,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FKP = 43,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMD = 45,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GHC = 46,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GIP = 47,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        XAU = 48,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GTQ = 49,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GNF = 50,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GYD = 51,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HTG = 52,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HNL = 53,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HKD = 54,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HUF = 55,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ISK = 56,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        INR = 57,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IDR = 58,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IQD = 59,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ILS = 60,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        JMD = 61,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        JPY = 62,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        JOD = 63,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        KZT = 64,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        KES = 65,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        KRW = 66,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        KWD = 67,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LAK = 68,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LVL = 69,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LBP = 70,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LSL = 71,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LRD = 72,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LYD = 73,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LTL = 74,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MOP = 75,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MKD = 76,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MGF = 77,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MWK = 78,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MYR = 79,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MVR = 80,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MTL = 81,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MRO = 82,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MUR = 83,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MXN = 84,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MDL = 85,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MNT = 86,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MAD = 87,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MZM = 88,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MMK = 89,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NAD = 90,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NPR = 91,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ANG = 92,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NZD = 93,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NIO = 94,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NGN = 95,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        KPW = 96,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NOK = 97,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OMR = 98,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        XPF = 99,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PKR = 100,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        XPD = 101,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PAB = 102,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PGK = 103,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PYG = 104,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PEN = 105,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PHP = 106,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        XPT = 107,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PLN = 108,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        QAR = 109,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ROL = 110,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RUB = 111,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WST = 112,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        STD = 113,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SAR = 114,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SCR = 115,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SLL = 116,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        XAG = 117,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SGD = 118,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SKK = 119,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SIT = 120,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SBD = 121,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SOS = 122,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ZAR = 123,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LKR = 124,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SHP = 125,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SDD = 126,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SRG = 127,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SZL = 128,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SEK = 129,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CHF = 130,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SYP = 131,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TWD = 132,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TZS = 133,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        THB = 134,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TOP = 135,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TTD = 136,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TND = 137,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TRL = 138,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        USD = 139,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AED = 140,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UGX = 141,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UAH = 142,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UYU = 143,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VUV = 144,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VEB = 145,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VND = 146,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        YER = 147,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        YUM = 148,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ZMK = 149,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ZWD = 150,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TRY = 151,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Currency", Namespace="http://www.restfulwebservices.net/DataContracts/2008/01")]
    [System.SerializableAttribute()]
    public partial class Currency : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Walkabout.RestfulWebServices.CurrencyCode FromCurrencyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Walkabout.RestfulWebServices.CurrencyCode ToCurrencyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double RateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Walkabout.RestfulWebServices.CurrencyCode FromCurrency {
            get {
                return this.FromCurrencyField;
            }
            set {
                if ((this.FromCurrencyField.Equals(value) != true)) {
                    this.FromCurrencyField = value;
                    this.RaisePropertyChanged("FromCurrency");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Walkabout.RestfulWebServices.CurrencyCode ToCurrency {
            get {
                return this.ToCurrencyField;
            }
            set {
                if ((this.ToCurrencyField.Equals(value) != true)) {
                    this.ToCurrencyField = value;
                    this.RaisePropertyChanged("ToCurrency");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public double Rate {
            get {
                return this.RateField;
            }
            set {
                if ((this.RateField.Equals(value) != true)) {
                    this.RateField = value;
                    this.RaisePropertyChanged("Rate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DefaultFaultContract", Namespace="http://GOTLServices.FaultContracts/2008/01")]
    [System.SerializableAttribute()]
    public partial class DefaultFaultContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ErrorIdField;
        
        private string ErrorMessageField;
        
        private System.Guid CorrelationIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ErrorId {
            get {
                return this.ErrorIdField;
            }
            set {
                if ((this.ErrorIdField.Equals(value) != true)) {
                    this.ErrorIdField = value;
                    this.RaisePropertyChanged("ErrorId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.Guid CorrelationId {
            get {
                return this.CorrelationIdField;
            }
            set {
                if ((this.CorrelationIdField.Equals(value) != true)) {
                    this.CorrelationIdField = value;
                    this.RaisePropertyChanged("CorrelationId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.restfulwebservices.net/ServiceContracts/2008/01", ConfigurationName="RestfulWebServices.ICurrencyService")]
    public interface ICurrencyService {
        
        [System.ServiceModel.OperationContractAttribute(Action="GetConversionRate", ReplyAction="http://www.restfulwebservices.net/ServiceContracts/2008/01/ICurrencyService/GetCo" +
            "nversionRateResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Walkabout.RestfulWebServices.DefaultFaultContract), Action="http://www.restfulwebservices.net/ServiceContracts/2008/01/ICurrencyService/GetCo" +
            "nversionRateDefaultFaultContractFault", Name="DefaultFaultContract", Namespace="http://GOTLServices.FaultContracts/2008/01")]
        Walkabout.RestfulWebServices.Currency GetConversionRate(Walkabout.RestfulWebServices.CurrencyCode FromCurrency, Walkabout.RestfulWebServices.CurrencyCode ToCurrency);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICurrencyServiceChannel : Walkabout.RestfulWebServices.ICurrencyService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CurrencyServiceClient : System.ServiceModel.ClientBase<Walkabout.RestfulWebServices.ICurrencyService>, Walkabout.RestfulWebServices.ICurrencyService {
        
        public CurrencyServiceClient() {
        }
        
        public CurrencyServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CurrencyServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CurrencyServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CurrencyServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Walkabout.RestfulWebServices.Currency GetConversionRate(Walkabout.RestfulWebServices.CurrencyCode FromCurrency, Walkabout.RestfulWebServices.CurrencyCode ToCurrency) {
            return base.Channel.GetConversionRate(FromCurrency, ToCurrency);
        }
    }
}
