<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows7.0</TargetFramework>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <UseWPF>true</UseWPF>
    <RootNamespace>Walkabout.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="ChartData.csv" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="ChartData.csv" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MyMoney\MyMoney.csproj" />
  </ItemGroup>

</Project>
