<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Grpc.Net.Client" Version="2.58.0" />
    <PackageReference Include="Grpc.Tools" Version="2.58.0">
      <PrivateAssets>All</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Google.Protobuf" Version="3.23.0" />
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="..\Protos\performance.proto" GrpcServices="Client">
      <Link>performance.proto</Link>
    </Protobuf>
  </ItemGroup>

</Project>
