//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Walkabout.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Walkabout.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account name cannot contain the characters &apos;{&apos;, &apos;}&apos; or &apos;:&apos;.
        /// </summary>
        internal static string AccountNameValidChars {
            get {
                return ResourceManager.GetString("AccountNameValidChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account &apos;{0}&apos; should be of type {1} in order to import these transactions..
        /// </summary>
        internal static string AccountTypeMismatch {
            get {
                return ResourceManager.GetString("AccountTypeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All files (*.*)|*.*.
        /// </summary>
        internal static string AllFileFilter {
            get {
                return ResourceManager.GetString("AllFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binary XML files (*.bxml)|*.bxml.
        /// </summary>
        internal static string BinaryXmlFileFilter {
            get {
                return ResourceManager.GetString("BinaryXmlFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV files (*.csv)|*.csv.
        /// </summary>
        internal static string CsvFileFilter {
            get {
                return ResourceManager.GetString("CsvFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account with name &apos;{0}&apos; already exists, would you like to use the existing account instead?.
        /// </summary>
        internal static string DuplicateAccount {
            get {
                return ResourceManager.GetString("DuplicateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Exists.
        /// </summary>
        internal static string DuplicateAccountCaption {
            get {
                return ResourceManager.GetString("DuplicateAccountCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error fetching stock quotes for query {0}.
        /// </summary>
        internal static string ErrorFetchingSymbols {
            get {
                return ResourceManager.GetString("ErrorFetchingSymbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge Security.
        /// </summary>
        internal static string MergeSecurityCaption {
            get {
                return ResourceManager.GetString("MergeSecurityCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Money Files (*.db)|*.db.
        /// </summary>
        internal static string MoneyFileFilter {
            get {
                return ResourceManager.GetString("MoneyFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Money SQL CE Files (*.MyMoney.sdf)|*.MyMoney.sdf.
        /// </summary>
        internal static string MoneySQLCEFileFilter {
            get {
                return ResourceManager.GetString("MoneySQLCEFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Money SQL Lite Files (*.mmdb)|*.mmdb|Old Money SQL Lite Files (*.MyMoney.db)|*.MyMoney.db.
        /// </summary>
        internal static string MoneySQLLiteFileFilter {
            get {
                return ResourceManager.GetString("MoneySQLLiteFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OFX files (*.ofx)|*.ofx.
        /// </summary>
        internal static string OfxFileFilter {
            get {
                return ResourceManager.GetString("OfxFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string PasswordPrompt {
            get {
                return ResourceManager.GetString("PasswordPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QFX files (*.qfx)|*.qfx.
        /// </summary>
        internal static string QfxFileFilter {
            get {
                return ResourceManager.GetString("QfxFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QIF files (*.qif)|*.qif.
        /// </summary>
        internal static string QifFileFilter {
            get {
                return ResourceManager.GetString("QifFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to delete the security &apos;{0}&apos; and move all investments referencing that old security to the new security you selected &apos;{1}&apos;.
        /// </summary>
        internal static string RenameSecurity {
            get {
                return ResourceManager.GetString("RenameSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot delete the security &apos;{0}&apos; because there are still {1} transactions referencing it.  You need to move those transactions to some other security first.  You can do that easily using drag/drop..
        /// </summary>
        internal static string SecurityDeleteDisabled {
            get {
                return ResourceManager.GetString("SecurityDeleteDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Disabled.
        /// </summary>
        internal static string SecurityDeleteDisabledCaption {
            get {
                return ResourceManager.GetString("SecurityDeleteDisabledCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol &apos;{0}&apos; contains illegal characters.
        /// </summary>
        internal static string SkippingSecurityIllegalSymbol {
            get {
                return ResourceManager.GetString("SkippingSecurityIllegalSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not updating security &apos;{0}&apos; because it has an empty stock symbol.
        /// </summary>
        internal static string SkippingSecurityMissingSymbol {
            get {
                return ResourceManager.GetString("SkippingSecurityMissingSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server Backup Files (*.dat)|*.dat.
        /// </summary>
        internal static string SqlServerBackupFileFilter {
            get {
                return ResourceManager.GetString("SqlServerBackupFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C means this transaction was entered manually but has cleared at your bank.
        /// </summary>
        internal static string StatusClearedTip {
            get {
                return ResourceManager.GetString("StatusClearedTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E means this was an electronically downloaded transaction.
        /// </summary>
        internal static string StatusElectronicTip {
            get {
                return ResourceManager.GetString("StatusElectronicTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R means this is a reconciled transaction.
        /// </summary>
        internal static string StatusReconciledTip {
            get {
                return ResourceManager.GetString("StatusReconciledTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V means this is a voided transaction.
        /// </summary>
        internal static string StatusVoidTip {
            get {
                return ResourceManager.GetString("StatusVoidTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Fetching Stock Quotes.
        /// </summary>
        internal static string StockQuoteErrorCaption {
            get {
                return ResourceManager.GetString("StockQuoteErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhanded exception processing stock quote results.
        /// </summary>
        internal static string StockQuotesException {
            get {
                return ResourceManager.GetString("StockQuotesException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock quote service quota has been exceeded, try again tomorrow..
        /// </summary>
        internal static string StockServiceQuotaExceeded {
            get {
                return ResourceManager.GetString("StockServiceQuotaExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock symbol {0} not found online.
        /// </summary>
        internal static string SymbolNotFound {
            get {
                return ResourceManager.GetString("SymbolNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer from closed account:.
        /// </summary>
        internal static string TransferFromClosedAccountPrefix {
            get {
                return ResourceManager.GetString("TransferFromClosedAccountPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer from: .
        /// </summary>
        internal static string TransferFromPrefix {
            get {
                return ResourceManager.GetString("TransferFromPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer to closed account: .
        /// </summary>
        internal static string TransferToClosedAccountPrefix {
            get {
                return ResourceManager.GetString("TransferToClosedAccountPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer to: .
        /// </summary>
        internal static string TransferToPrefix {
            get {
                return ResourceManager.GetString("TransferToPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TXF File (.txf)|*.txf.
        /// </summary>
        internal static string TurboTaxFileFilter {
            get {
                return ResourceManager.GetString("TurboTaxFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The scanning device is busy..
        /// </summary>
        internal static string WIA_ERROR_BUSY {
            get {
                return ResourceManager.GetString("WIA_ERROR_BUSY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The cover is open.
        /// </summary>
        internal static string WIA_ERROR_COVER_OPEN {
            get {
                return ResourceManager.GetString("WIA_ERROR_COVER_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in scanner destination..
        /// </summary>
        internal static string WIA_ERROR_DESTINATION {
            get {
                return ResourceManager.GetString("WIA_ERROR_DESTINATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unspecified error occurred during an attempted communication with the scanner..
        /// </summary>
        internal static string WIA_ERROR_DEVICE_COMMUNICATION {
            get {
                return ResourceManager.GetString("WIA_ERROR_DEVICE_COMMUNICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The scanner head is locked.
        /// </summary>
        internal static string WIA_ERROR_DEVICE_LOCKED {
            get {
                return ResourceManager.GetString("WIA_ERROR_DEVICE_LOCKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The device driver threw an exception..
        /// </summary>
        internal static string WIA_ERROR_EXCEPTION_IN_DRIVER {
            get {
                return ResourceManager.GetString("WIA_ERROR_EXCEPTION_IN_DRIVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error has occurred with the scanning device..
        /// </summary>
        internal static string WIA_ERROR_GENERAL_ERROR {
            get {
                return ResourceManager.GetString("WIA_ERROR_GENERAL_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is an incorrect setting on the scanner..
        /// </summary>
        internal static string WIA_ERROR_INCORRECT_HARDWARE_SETTING {
            get {
                return ResourceManager.GetString("WIA_ERROR_INCORRECT_HARDWARE_SETTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The device does not support this command.
        /// </summary>
        internal static string WIA_ERROR_INVALID_COMMAND {
            get {
                return ResourceManager.GetString("WIA_ERROR_INVALID_COMMAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The response from the driver is invalid..
        /// </summary>
        internal static string WIA_ERROR_INVALID_DRIVER_RESPONSE {
            get {
                return ResourceManager.GetString("WIA_ERROR_INVALID_DRIVER_RESPONSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The scanner device was deleted. It can no longer be accessed.
        /// </summary>
        internal static string WIA_ERROR_ITEM_DELETED {
            get {
                return ResourceManager.GetString("WIA_ERROR_ITEM_DELETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The lamp is off.
        /// </summary>
        internal static string WIA_ERROR_LAMP_OFF {
            get {
                return ResourceManager.GetString("WIA_ERROR_LAMP_OFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network reservation failed.
        /// </summary>
        internal static string WIA_ERROR_NETWORK_RESERVATION_FAILED {
            get {
                return ResourceManager.GetString("WIA_ERROR_NETWORK_RESERVATION_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The scanning device is not online..
        /// </summary>
        internal static string WIA_ERROR_OFFLINE {
            get {
                return ResourceManager.GetString("WIA_ERROR_OFFLINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user requested a scan and there are no documents left in the document feeder..
        /// </summary>
        internal static string WIA_ERROR_PAPER_EMPTY {
            get {
                return ResourceManager.GetString("WIA_ERROR_PAPER_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paper is jammed in the scanner&apos;s document feeder..
        /// </summary>
        internal static string WIA_ERROR_PAPER_JAM {
            get {
                return ResourceManager.GetString("WIA_ERROR_PAPER_JAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unspecified problem occurred with the scanner&apos;s document feeder.
        /// </summary>
        internal static string WIA_ERROR_PAPER_PROBLEM {
            get {
                return ResourceManager.GetString("WIA_ERROR_PAPER_PROBLEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unspecified error has occurred with the scanner that requires user intervention. The user should ensure that the device is turned on, online, and any cables are properly connected..
        /// </summary>
        internal static string WIA_ERROR_USER_INTERVENTION {
            get {
                return ResourceManager.GetString("WIA_ERROR_USER_INTERVENTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The scanner is warming up..
        /// </summary>
        internal static string WIA_ERROR_WARMING_UP {
            get {
                return ResourceManager.GetString("WIA_ERROR_WARMING_UP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML files (*.xml)|*.xml.
        /// </summary>
        internal static string XmlFileFilter {
            get {
                return ResourceManager.GetString("XmlFileFilter", resourceCulture);
            }
        }
    }
}
